### ISSUE TITLE
Plan

### ISSUE THREAD

**Issue by ai** [luisrudge/postcss-flexbugs-fixes#1]
There are many people want to help you.

So I think you should create a plan to stay turned.

**Comment by luisrudge** [comment]
Yep. I agree. I'll create a bunch of issues for each one of the flexbug's bug and we'll go from there.

**Comment by luisrudge** [comment]
Ok, [Issues created](https://github.com/luisrudge/postcss-flexbugs-fixes/labels/flexbug) and [npm package published](https://www.npmjs.com/package/postcss-flexbugs-fixes).

**Comment by ai** [comment]
Nice, I will promote it by PostCSS twitter on next week.

**Comment by luisrudge** [comment]
Ok, Thanks!
