### ISSUE TITLE
The Flexbug 3 fix may break sites

### ISSUE THREAD

**Issue by philipwalton** [luisrudge/postcss-flexbugs-fixes#18]
Swapping `min-height` for `height` in all situation doesn't seem like a good idea as they're very different things.

Also, I've recently updated that bug with a new workaround so `min-height` works in IE 10-11.

**Comment by luisrudge** [comment]
what do you suggest?

**Comment by philipwalton** [comment]
Honestly, I just wouldn't try to fix this one. Let users handle it in the HTML.
