### ISSUE TITLE
Send PR to PostCSS README

### ISSUE THREAD

**Issue by ai** [luisrudge/postcss-flexbugs-fixes#20]
You should add this awesome plugin to Plugins section in PostCSS README. Wait for your PR.

I think “Others” section will be best match.

**Comment by luisrudge** [comment]
We have some rough edges to fix yet, but I'll add this repo when we fix some conceptual issues

**Comment by ai** [comment]
Ping :)

**Comment by luisrudge** [comment]
Pong! I discovered that most of the fixes can't be really fixed without more context about where the class is being used. See #9, #17 and #18.
Maybe I should just fix what can be fixed for sure, and go with that?

**Comment by ai** [comment]
Warnings will be OK in this case.

But you definetly should send PR to PostCSS :)

**Comment by luisrudge** [comment]
Ok. Let me remove some danger-ish code and I'll submit the PR

**Comment by luisrudge** [comment]
Done! https://github.com/postcss/postcss/pull/540
