### ISSUE TITLE
`flex: inherit` processed into invalid property

### ISSUE THREAD

**Issue by henwen** [luisrudge/postcss-flexbugs-fixes#29]
`flex: inherit` is processed as `flex: inherit 1 0%;`, which is an invalid property value (in webkit browsers at least).

PS - Thanks for the great plugin. It's been a lifesaver.

**Comment by luisrudge** [comment]
inherit should keep as inherit, right?

**Comment by henwen** [comment]
Correct - keeping it as `inherit` will set the three values that`flex:` shorthands to `inherit`, which is valid. 

On Tue, Dec 06, 2016 at 12:29 PM "Luís Rudge"

<
mailto:
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

inherit should keep as inherit, right?

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/luisrudge/postcss-flexbugs-fixes/issues/29#issuecomment-265231150
, or

**Comment by luisrudge** [comment]
published to `postcss-flexbugs-fixes@2.1.0`.

Thanks for catching that!
