### ISSUE TITLE
Bug 4: Why flex basis of 0% instead of auto?

### ISSUE THREAD

**Issue by RoelN** [luisrudge/postcss-flexbugs-fixes#30]
When not explicitly set, `flex-basis` is `auto`, according to [MDN](https://developer.mozilla.org/en/docs/Web/CSS/flex). So you'd expect

`flex: 1;`

to be rewritten to

`flex: 1 1 auto;`

But the plugin uses `0%` instead of `auto`, which yields different results. At least in IE10, a `flex-basis` of `0%` will prevent the element from growing.

**Comment by luisrudge** [comment]
I just followed the workaround showed here: https://github.com/philipwalton/flexbugs/blob/master/README.md#4-flex-shorthand-declarations-with-unitless-flex-basis-values-are-ignored

**Comment by RoelN** [comment]
That bug seems to be about using a unitless flex basis in the flex shorthand (e.g. `flex: 1 0 0;`) but is not about an _unset_ `flex-basis` value (e.g. `flex: 1;`). When using the latter, it is expected that the two values you don't explicitly set are kept at their defaults: `1` for 'flex-shrink` and `auto` for `flex-basis`.

**Comment by luisrudge** [comment]
Ops, sorry. I meant this bug: https://github.com/philipwalton/flexbugs/blob/master/README.md#6-the-default-flex-value-has-changed

![image](https://cloud.githubusercontent.com/assets/941075/21893759/2dd293f4-d8bb-11e6-8d3f-9260570e6252.png)

They say `flex: 1` is the same thing as `flex: 1 1 0%`

In fact, if I add `flex: 1` to any html element using chrome dev tools, it says that the defaults are `1 1 0%`:

![image](https://cloud.githubusercontent.com/assets/941075/21893821/7d335474-d8bb-11e6-8410-fd744708ac94.png)

**Comment by RoelN** [comment]
Ah yes, you are right. Upon closer inspection, it indeed said so in the page I linked:

>  Defaults to 0% when omitted.

**Comment by Zephir77167** [comment]
Hey, I am stumbling on this. Currently, my websites works on all browsers _except_ IE. I would like to support IE11. I am using autoprefixer, with browserslist (last 1 version), and this (awesome) plugin.

Now I just came to understand that the only thing which makes it NOT work, is `flex: 1 1 0%;`. When changing it to `flex: 1 1 auto;`, the site works like a charm.

I know that Chrome defaults `flex: 1;` to `flex: 1 1 0%;`, but, as IE11 is using `flex` and not `-ms-flex`, both have to be compatible.

How do you guys manage IE? Should we handle it at this lib level? Or should I open this issue on the autoprefixer repo?

Thanks in advance!

**Comment by luisrudge** [comment]
@Zephir77167 what is the default on IE11?

**Comment by Zephir77167** [comment]
Sorry, forgot to note it; IE11 defaults `flex: 1;` to `flex: 1 1 0px;`. I just tested and it is as broken as `flex: 1 1 0%;`.

**Comment by Zephir77167** [comment]
Nevermind, I just realized that is is a manifestation of [Bug #7](https://codepen.io/philipwalton/pen/ZYLdqb) :(
