### ISSUE TITLE
Can this be used with gulp?

### ISSUE THREAD

**Issue by nullbio** [luisrudge/postcss-flexbugs-fixes#31]
Just wondering if I can use this with gulp directly, i.e. something like:

```
var fix = require('postcss-flexbugs-fixes')

gulp.src('*').pipe(fix()).pipe(gulp.dest('dist'))
```

**Comment by luisrudge** [comment]
please refer to [this guide](https://github.com/postcss/gulp-postcss#passing-plugins-directly) on how to use postcss with gulp. Thanks!
