### ISSUE TITLE
Support `postcss` v6

### ISSUE THREAD

**Issue by evilebottnawi** [luisrudge/postcss-flexbugs-fixes#34]
:+1:

**Comment by luisrudge** [comment]
can you send a PR?

**Comment by evilebottnawi** [comment]
@luisrudge let's do this :+1:

**Comment by evilebottnawi** [comment]
Done in https://github.com/luisrudge/postcss-flexbugs-fixes/pull/35

**Comment by luisrudge** [comment]
Ops, forgot to close this. Thanks 🎉
