### ISSUE TITLE
Flex shorthand without flex-shrink is not working

### ISSUE THREAD

**Issue by casey6** [luisrudge/postcss-flexbugs-fixes#39]
When using the flex shorthand both flex-shrink and flex-basis are optional. But if only two values are provided, the second value may be either the flex-shrink or flex-basis property. This use case isn't supported with this plugin, and the resulting code is incorrect.

Another way to say it is that the flex-shrink value has to be a number. So if the second value provided in a flex shorthand declaration is not a number, it must be the flex-basis.

Given this code: 
```css
flex: 1 30px;
```

We should get this:
```css
flex: 1 0 30px;
```

But instead we get this:
```css
flex: 1 30px 0%;
```

**Comment by luisrudge** [comment]
How can we tell if the second value should be flex-shrink or flex-basis?

**Comment by casey6** [comment]
[Flex-shrink](https://www.w3.org/TR/css-flexbox-1/#flex-shrink-property) can only be a number, [flex-basis](https://www.w3.org/TR/css-flexbox-1/#flex-basis-property) can be a length or keyword. 

Checking if the second value is a number might be a simple enough solution.

**Comment by luisrudge** [comment]
Awesome. Can you make a PR with this and add a test case?

**Comment by luisrudge** [comment]
fixed in #41. released in the 3.2.0 version
