### ISSUE TITLE
in which order these postcss plugins shall be loaded ?

### ISSUE THREAD

**Issue by kapouer** [luisrudge/postcss-flexbugs-fixes#49]
Hi,

i'm using these:
postcssImport
postcssUrl
autoprefixer
csswring

I'm trying to add postcss-flexbugs-fixes but i'm not sure if autoprefixer, or csswring, are going to screw it up or what.

Could you help me on this ?

**Comment by kapouer** [comment]
I'm doing it there: https://github.com/kapouer/postinstall-css/blob/master/index.js

**Comment by luisrudge** [comment]
I have no idea as well.. I guess you should write a small css file and try different approaches to see what is the best result.
