### ISSUE TITLE
Flexbug4 - flex shorthand declarations with unitless flex-basis values are ignored

### ISSUE THREAD

**Issue by luisrudge** [luisrudge/postcss-flexbugs-fixes#5]
https://github.com/philipwalton/flexbugs/blob/master/README.md#4-flex-shorthand-declarations-with-unitless-flex-basis-values-are-ignored

**Comment by kadmil** [comment]
I'm in!

**Comment by kadmil** [comment]
There's a nasty thing.

The bug could be fixed by adding '0%' to every flex declaration, I've wrote code to o this and stumbled upon broken tests. This fix apparently breaks everyone not expecting extra parts to be added on flex property shorthand.

As I can see, we have two options: 1) Change expectations for other tests; and 2) change flex shorthand to full-blown three-property thing on each build.

All no good, I'm looking for your advice.

**Comment by kadmil** [comment]
https://github.com/luisrudge/postcss-flexbugs-fixes/pull/15

Added code for you to see.

**Comment by luisrudge** [comment]
I think the right thing to do is to add 0% only if the declaration is `flex: [0-9] [0-9] 0`.  If the declaration is `flex: 1`, we should leave as it is, since the bug won't apply. What do you think

**Comment by kadmil** [comment]
Now only flex: x y 0; and flex: x y 0px; are changed to flex: x y 0%;
It looks like in IE we have problem without declaration like flex: 1 1 auto; — flexbox container don't grow as it should. Maybe it's another bug, but originally I've looked for solution in this one.
Another thing is, there's a bug on changed default values for flex in IE (6-th), and we're fixing them by no extra code.

So, is it ok to leave solution or it's better to implement another?

**Comment by luisrudge** [comment]
are you sure it's the 6th bug? https://github.com/philipwalton/flexbugs#6-the-default-flex-value-has-changed

**Comment by kadmil** [comment]
Yes, it's about default flex-shrink: 0 in IE 10 and workaround with explicitly specifying it in properties. I've added spec for test, but it's covered with bug4.js code.

**Comment by kadmil** [comment]
Speaking on flex declarations without flex-basis part, it looks like IE fails to understand them and the container doesn't grow. It was my initial problem then I've started looking for any postcss-solution.

**Comment by luisrudge** [comment]
Ok. I'll clone your fork later tonight and give it a go. Can you please add the readme modifications?

**Comment by kadmil** [comment]
Done. )

**Comment by luisrudge** [comment]
Damn. Sorry! I forgot about this!

**Comment by luisrudge** [comment]
I'm reviewing it now

**Comment by luisrudge** [comment]
fixed by #16

**Comment by luisrudge** [comment]
Thanks @kadmil!

**Comment by kadmil** [comment]
Glad it's working! ))
