### ISSUE TITLE
Version 4.0.0 Changelog

### ISSUE THREAD

**Issue by tomciopp** [luisrudge/postcss-flexbugs-fixes#52]
It looks like version 4 was published, but there has been no update to the Changelog detailing what the breaking changes are.

**Comment by ChristianStornowski** [comment]
## 4.0.0
* upgrade to postcss 7

:-D

**Comment by luisrudge** [comment]
Sorry, my bad. Forgot to commit: 
![image](https://user-images.githubusercontent.com/941075/42946762-217faa7a-8b42-11e8-9bf8-6064ff3f92e2.png)
