### ISSUE TITLE
Flex items and min-width:0

### ISSUE THREAD

**Issue by AndrejGajdos** [luisrudge/postcss-flexbugs-fixes#63]
What do you think of adding `min-width:0` to flex items?

It helps to avoid unexpected behaviour of flex items. [flex-items-and-min-width-0](https://dfmcphee.com/flex-items-and-min-width-0/)

**Comment by luisrudge** [comment]
Too intrusive. This lib can't make that decision by itself and it's up to the developer to add something like that.
