### ISSUE TITLE
PostCSS plugin postcss-flexbugs-fixes requires PostCSS 8

### ISSUE THREAD

**Issue by Lakshmi-Narasimha** [luisrudge/postcss-flexbugs-fixes#80]
Hi 

I am getting below error when I am using PostCss 8.

PostCSS plugin postcss-flexbugs-fixes requires PostCSS 8

**Comment by luisrudge** [comment]
You're probably using postcss 7.x. Update to postcss 8.

**Comment by joneslloyd** [comment]
I'm getting the same error when I'm definitely using postcss 8.
